### ISSUE TITLE
Unable to sign in.

### ISSUE THREAD

**Issue by Kralizek** [patriksvensson/ghostly#4]
When I click the "Sign in using external browser" button, nothing happens.

I'm running on Windows 11.

**Comment by patriksvensson** [comment]
Fixed in 1.18.0 (#3)

**Comment by patriksvensson** [comment]
If you're building from source you will need to run the bootstrap script first.

**Comment by mediaexplorer74** [comment]
> If you're building from source you will need to run the bootstrap script first.

Hi )) Is your Ghosly project still (a)live? Cool.

I have veery slow and pooor dev machine from 2006 year. No bootstrap, no NodeJS, etc.. ==))) So, please please please share GitHubSecrets.Generated.cs. I only want to repeat your own words: "client ID and client secret does not grant you any rights on behalf of the user who created it, so even though it's not the end of the world". 
Reason: I want to Windows10Mobile compatibility (min. win sdk - 15063) and use Ghostly on my old sweet retro-phone Nokia Lumia :))

Cheers up, 
  " Ghost " =)

**Comment by patriksvensson** [comment]
Hi, Ghostly is in maintenance mode.

You will need to generate your own credentials or download Ghostly from the Microsoft store.

**Comment by mediaexplorer74** [comment]
> Hi, Ghostly is in maintenance mode.

Oh, maintenance mode? So strange... Of cause, I m very stupid developer-hobbyist... but it really sounds strange (You are at your GitHub zone, all systems work normally, khmmm). I don't need your exact idclient + secret. I'm interested in only GitHubSecrets.Generated.cs file/code structure :) 
P.S. I have my own [Ghostly's analog](https://github.com/mediaexplorer74/githubx), so I undestand how to register the new OAuth app and copy-paste clientid/secret... =)
Best ,
Andrey aka MediaExplorer

Edit: I solved my "problem" via editing GitHubSecrets.cs:
```
public bool IsValid()
{
    /*
    string value = null;
    GetClientId(ref value);
    if (value == null)
    {
        return false;
    }

    GetClientSecret(ref value);
    if (value == null)
    {
        return false;
    }
    */

    return true;
}

 public string ClientId
 {
     get
     {
         string value = "e********************";//null;
         //GetClientId(ref value);
         if (value == null)
         {
             throw new InvalidOperationException("No client ID specified");
         }

         return value;
     }
 }

 public string ClientSecret
 {
     get
     {
         string value = "2********************************";//null;
         //GetClientSecret(ref value);
         if (value == null)
         {
             throw new InvalidOperationException("No client secret specified");
         }

         return value;
     }
 }



```

Also I "blocked" globals.json because of I don't want to use any NET 6 / 7 / 8 :)

Waw, your solution compiled / started successfully at now :

![image](https://github.com/patriksvensson/ghostly/assets/12032735/308b0410-3cbf-410e-87e5-270f364cdd20)

![image](https://github.com/patriksvensson/ghostly/assets/12032735/60948d77-4258-4986-877e-c1b09092620a)
