### ISSUE TITLE
I have missing issues

### ISSUE THREAD

**Issue by clicketyclackety** [patriksvensson/ghostly#7]
**Describe the bug**
I have created a new filter to show me all of my issues with either of 2 labels by using the below syntax
``` python
is:issue AND label = "01 High priority ★★★" OR label = "00 Highest Priority 🔥🔥🔥" AND NOT label =  "wontfix"
```
However, even by just using the below I don't get any issues listed, when I do have one active in my repo
``` python
label = "00 Highest Priority 🔥🔥🔥"
```
![image](https://user-images.githubusercontent.com/28632338/147971670-d63c390b-a1ba-4d52-a837-6b4c9361352e.png)

**To Reproduce**
1. Create a new issue
2. Add the same label as I have "00 Highest Priority 🔥🔥🔥"
2. Refresh Ghostly

**Expected behavior**
I expected my issues to appear, but they are absent from Ghostly entirely.
![image](https://user-images.githubusercontent.com/28632338/147971967-ae0751e6-7865-49a9-997a-4a8ccc385cb1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 (x64)
 - Version: 1.18.0

**Additional context**
I checked the logs and could not find anything that mentioned the missing issue.

**Comment by patriksvensson** [comment]
@clicketyclackety I cannot reproduce this issue.

I'm also a bit confused since you're showing the `Inbox` in your example which you cannot assign filters to.
Are you trying to show that the issue in question isn't synchronized at all?

**Ghostly only synchronizes read notifications 30 days back**.
All unread notifications will automatically synchronize.

I also noted that your expression (probably) is invalid in one place.
The `OR` keyword has higher precedence than `AND`, so your expression will look something like this:

```
Or(
    And(
        Equals(Property(issue), Constant(True)),
        Equals(Collection(label), StringLiteral('01 High priority ★★★'))),
    And(
        Equals(Collection(label), StringLiteral('00 Highest Priority 🔥🔥🔥')),
        Not(Equals(Collection(label), StringLiteral('wontfix')))))
```

I assume that you want the following expression instead:

```
is:issue 
AND (label = "01 High priority ★★★" OR label = "00 Highest Priority 🔥🔥🔥") 
AND NOT label =  "wontfix"
```

**Comment by clicketyclackety** [comment]
Hi @patriksvensson,
Yes sorry, I was trying to show it didn't show at all. I see. That makes sense, so it's ONLY filtering notifications, sorry I have misunderstood slightly what Ghostly does!
And yes that looks better to me :)
